# Generated by Django 5.0.7 on 2024-08-12 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_slideshowimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slideshowimage",
            old_name="description",
            new_name="title",
        ),
    ]
