# Generated by Django 5.0.7 on 2024-08-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slideshow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slideshowimage",
            name="title",
        ),
        migrations.AddField(
            model_name="slideshowimage",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="slideshowimage",
            name="image",
            field=models.ImageField(upload_to="slideshow/"),
        ),
    ]
